export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const INCREMENT = 'INCREMENT'
export const FILTER_SELECT_CHANGE = 'FILTER_SELECT_CHANGE'
export const FILTER_DATERANGE_CHANGE = 'FILTER_DATERANGE_CHANGE'